version: "3.9"
services:
  ngrok:
    image: ngrok/ngrok
    environment:
    - NGROK_AUTHTOKEN
    ports:
      - 4040:4040
    command: http atlantis:4141
  
  atlantis:
    image: ghcr.io/runatlantis/atlantis:{latest version}
    environment:
    - ATLANTIS_ATLANTIS_URL
    - ATLANTIS_GH_USER
    - ATLANTIS_GH_TOKEN
    - ATLANTIS_GH_WEBHOOK_SECRET
    - ATLANTIS_REPO_ALLOWLIST
    - ATLANTIS_REPO_CONFIG
    volumes:
      - $PWD/config/:/config/
